/**
 * useOnChainAMM — ethers.js hook for real on-chain interactions
 *
 * When contracts.json exists (post-deploy) AND MetaMask is connected
 * to the correct network, swap/liquidity calls go to the actual blockchain.
 * Falls back silently to the API (simulation) when not available.
 */

import { useState, useEffect, useCallback } from 'react';

// ABIs (minimal — only what the frontend needs)
const AMM_ABI = [
  'function getReserves() view returns (uint256, uint256, uint32)',
  'function getSpotPrice() view returns (uint256)',
  'function getAmountOut(uint256, uint256, uint256) pure returns (uint256)',
  'function swapWithProtection(address, uint256, uint256, uint256) returns (uint256)',
  'function addLiquidity(uint256, uint256) returns (uint256)',
  'function removeLiquidity(uint256) returns (uint256, uint256)',
  'function balanceOf(address) view returns (uint256)',
  'function totalSupply() view returns (uint256)',
  'function tokenA() view returns (address)',
  'function tokenB() view returns (address)',
  'event Swap(address indexed, address indexed, address indexed, uint256, uint256, uint256, address)',
];

const ERC20_ABI = [
  'function balanceOf(address) view returns (uint256)',
  'function allowance(address, address) view returns (uint256)',
  'function approve(address, uint256) returns (bool)',
  'function decimals() view returns (uint8)',
  'function symbol() view returns (string)',
];

const ROUTER_ABI = [
  'function getAmountsOut(uint256, address[]) view returns (uint256[])',
  'function swapExactIn(uint256, uint256, address[], address, uint256) returns (uint256[])',
];

// Supported chains
const SUPPORTED_CHAINS = {
  11155111: { name: 'Sepolia',     rpc: 'https://ethereum-sepolia-rpc.publicnode.com' },
  84532:    { name: 'Base Sepolia', rpc: 'https://sepolia.base.org' },
  1337:     { name: 'Localhost',   rpc: 'http://127.0.0.1:8545' },
  31337:    { name: 'Hardhat',     rpc: 'http://127.0.0.1:8545' },
};

// Load deployed addresses (generated by deploy script)
let CONTRACTS = null;
async function loadContracts() {
  if (CONTRACTS) return CONTRACTS;
  try {
    const r = await fetch('/contracts.json');
    if (r.ok) CONTRACTS = await r.json();
  } catch {}
  return CONTRACTS;
}

// Pool → contract name mapping
const POOL_CONTRACT_MAP = {
  'TKA/TKB':  'AMM_TKA_TKB',
  'TKA/USDC': 'AMM_TKA_USDC',
};

export function useOnChainAMM() {
  const [provider,    setProvider]    = useState(null);
  const [signer,      setSigner]      = useState(null);
  const [chainId,     setChainId]     = useState(null);
  const [contracts,   setContracts]   = useState(null);
  const [isOnChain,   setIsOnChain]   = useState(false);
  const [wrongNetwork, setWrongNetwork] = useState(false);

  // Init ethers when MetaMask is available
  useEffect(() => {
    if (typeof window === 'undefined' || !window.ethereum) return;

    const init = async () => {
      try {
        // Dynamic import of ethers to avoid SSR issues
        const { BrowserProvider } = await import('ethers');
        const p = new BrowserProvider(window.ethereum);
        const network = await p.getNetwork();
        const cid = Number(network.chainId);
        setChainId(cid);
        setProvider(p);

        const addrs = await loadContracts();
        setContracts(addrs);

        const supported = SUPPORTED_CHAINS[cid];
        if (!supported) { setWrongNetwork(true); return; }
        setWrongNetwork(false);

        // Only set signer if accounts are already connected
        const accounts = await window.ethereum.request({ method: 'eth_accounts' });
        if (accounts[0] && addrs) {
          const s = await p.getSigner();
          setSigner(s);
          setIsOnChain(true);
        }
      } catch (e) {
        console.warn('useOnChainAMM init failed:', e.message);
      }
    };

    init();

    const handleChain    = () => init();
    const handleAccounts = () => init();
    window.ethereum.on('chainChanged',    handleChain);
    window.ethereum.on('accountsChanged', handleAccounts);
    return () => {
      window.ethereum.removeListener('chainChanged',    handleChain);
      window.ethereum.removeListener('accountsChanged', handleAccounts);
    };
  }, []);

  // ── Get AMM contract instance for a pool ────────────────────────────────────
  const getAMMContract = useCallback(async (poolId) => {
    if (!signer || !contracts) return null;
    const { Contract } = await import('ethers');
    const contractName = POOL_CONTRACT_MAP[poolId];
    const addr = contracts?.contracts?.[contractName];
    if (!addr || !addr.startsWith('0x')) return null;
    return new Contract(addr, AMM_ABI, signer);
  }, [signer, contracts]);

  const getERC20 = useCallback(async (address) => {
    if (!signer) return null;
    const { Contract } = await import('ethers');
    return new Contract(address, ERC20_ABI, signer);
  }, [signer]);

  // ── Approve helper ──────────────────────────────────────────────────────────
  const ensureAllowance = useCallback(async (tokenAddress, spender, amount) => {
    const token = await getERC20(tokenAddress);
    if (!token || !signer) return;
    const owner     = await signer.getAddress();
    const allowance = await token.allowance(owner, spender);
    const { parseEther, MaxUint256 } = await import('ethers');
    if (allowance < BigInt(amount)) {
      const tx = await token.approve(spender, MaxUint256);
      await tx.wait();
    }
  }, [getERC20, signer]);

  // ── On-chain swap ───────────────────────────────────────────────────────────
  const executeSwapOnChain = useCallback(async ({
    poolId, tokenIn, amountIn, minAmountOut, slippageBps = 50
  }) => {
    const amm = await getAMMContract(poolId);
    if (!amm) throw new Error('Contract not available');

    const { parseEther, formatEther } = await import('ethers');

    // Get token addresses
    const tokenAAddr = await amm.tokenA();
    const tokenBAddr = await amm.tokenB();
    const tokenInAddr = tokenIn === 'A' ? tokenAAddr : tokenBAddr;
    const ammAddr = await amm.getAddress();

    // Approve
    const amountInWei = parseEther(String(amountIn));
    await ensureAllowance(tokenInAddr, ammAddr, amountInWei);

    // Get quote for minAmountOut
    const [rA, rB] = await amm.getReserves();
    const rIn  = tokenIn === 'A' ? rA : rB;
    const rOut = tokenIn === 'A' ? rB : rA;
    const amtOut = await amm.getAmountOut(amountInWei, rIn, rOut);
    const minOut = amtOut * BigInt(10000 - slippageBps) / BigInt(10000);
    const deadline = BigInt(Math.floor(Date.now() / 1000) + 1200); // +20 min

    // Execute
    const tx = await amm.swapWithProtection(tokenInAddr, amountInWei, minOut, deadline);
    const receipt = await tx.wait();

    return {
      txHash:    receipt.hash,
      amountOut: formatEther(amtOut),
      gasUsed:   receipt.gasUsed.toString(),
    };
  }, [getAMMContract, ensureAllowance]);

  // ── On-chain add liquidity ──────────────────────────────────────────────────
  const addLiquidityOnChain = useCallback(async ({ poolId, amountA, amountB }) => {
    const amm = await getAMMContract(poolId);
    if (!amm) throw new Error('Contract not available');

    const { parseEther, formatEther } = await import('ethers');
    const ammAddr  = await amm.getAddress();
    const tokenAAddr = await amm.tokenA();
    const tokenBAddr = await amm.tokenB();
    const aWei = parseEther(String(amountA));
    const bWei = parseEther(String(amountB));

    await ensureAllowance(tokenAAddr, ammAddr, aWei);
    await ensureAllowance(tokenBAddr, ammAddr, bWei);

    const tx      = await amm.addLiquidity(aWei, bWei);
    const receipt = await tx.wait();
    return { txHash: receipt.hash, gasUsed: receipt.gasUsed.toString() };
  }, [getAMMContract, ensureAllowance]);

  // ── On-chain remove liquidity ───────────────────────────────────────────────
  const removeLiquidityOnChain = useCallback(async ({ poolId, liquidity }) => {
    const amm = await getAMMContract(poolId);
    if (!amm) throw new Error('Contract not available');

    const { parseEther, formatEther } = await import('ethers');
    const liqWei  = parseEther(String(liquidity));
    const tx      = await amm.removeLiquidity(liqWei);
    const receipt = await tx.wait();
    return { txHash: receipt.hash, gasUsed: receipt.gasUsed.toString() };
  }, [getAMMContract]);

  // ── Token balances ──────────────────────────────────────────────────────────
  const getTokenBalances = useCallback(async (poolId) => {
    if (!signer || !contracts) return null;
    const amm = await getAMMContract(poolId);
    if (!amm) return null;

    const { formatEther } = await import('ethers');
    const owner  = await signer.getAddress();
    const tA = await getERC20(await amm.tokenA());
    const tB = await getERC20(await amm.tokenB());
    if (!tA || !tB) return null;

    const [balA, balB, lpBal] = await Promise.all([
      tA.balanceOf(owner),
      tB.balanceOf(owner),
      amm.balanceOf(owner),
    ]);
    return {
      tokenA: formatEther(balA),
      tokenB: formatEther(balB),
      lp:     formatEther(lpBal),
    };
  }, [signer, contracts, getAMMContract, getERC20]);

  // ── Switch network ──────────────────────────────────────────────────────────
  const switchToSepolia = useCallback(async () => {
    if (!window.ethereum) return;
    try {
      await window.ethereum.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: '0xaa36a7' }], // Sepolia
      });
    } catch (e) {
      if (e.code === 4902) {
        await window.ethereum.request({
          method: 'wallet_addEthereumChain',
          params: [{
            chainId: '0xaa36a7',
            chainName: 'Sepolia Testnet',
            rpcUrls: ['https://ethereum-sepolia-rpc.publicnode.com'],
            nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 18 },
            blockExplorerUrls: ['https://sepolia.etherscan.io'],
          }],
        });
      }
    }
  }, []);

  const networkName = SUPPORTED_CHAINS[chainId]?.name || (chainId ? `Chain ${chainId}` : null);

  return {
    isOnChain,
    wrongNetwork,
    chainId,
    networkName,
    contracts,
    executeSwapOnChain,
    addLiquidityOnChain,
    removeLiquidityOnChain,
    getTokenBalances,
    switchToSepolia,
  };
}
